###
GET http://localhost:3000/api/books HTTP/1.1

###
GET http://localhost:8800 HTTP/1.1

###
GET http://localhost:3000/api/books?genre=Fantasy HTTP/1.1


###
GET http://localhost:3000/api/books/6124c2ecdbbbd170f4a3bbde HTTP/1.1

###
POST http://localhost:3000/api/books HTTP/1.1
content-type: application/json

{ "read":false,
  "title":"love story",
  "genre":"Fantasy",
  "author":"Pet store" }

###
PUT http://localhost:3000/api/books/612876c89815eb05d0e881fb HTTP/1.1
content-type: application/json

{ "read":false,
  "title":"love story2",
  "genre":"Fantasy",
  "author":"Pet store" }

###
DELETE http://localhost:3000/api/books/612892ec80081007cefc4ded HTTP/1.1
content-type: application/json

{ "title": "cross over this piece"
   }